Node A Name,Node B Name,# Connections,# Connections Unique,Type,Node A ID,Node B ID
Node A Name,Node B Name,0,0,Node A Name,Node A ID,Node B ID
DSCore.List.Transpose@var[]..[],DSOffice.Data.ExportExcel@string_string_int_int_var[][]_bool,6,5,DSCore,db067dc59e0147bda0cf858b0da3fc97,74aaea7e6e4546088068f93bcfc61ff2
DSOffice.Data.ImportExcel@var_string_bool_bool,DSCore.List.Transpose@var[]..[],0,0,DSOffice,c692d78907aa4d9ebaa4244cb92c20e4,b76189ba8c4a49dd875ddc88e806d5df
DSCore.List.GetItemAtIndex@var[]..[]_int,Revit.Elements.Element.SetParameterByName@string_var,78,58,DSCore,a2d2a3d30ff14eaaa120993bca904c53,d625ac5a20cd40ab88760f2266110977
DSCore.Math.Sum@double[],/@var[]..[]_var[]..[],3,2,DSCore,b5b8be87676947c48a5cc2d7c0af965e,ab84b72bd6754671b106d73f0f4fe7f8
GetValues@var[]..[],DSCore.Math.Sum@double[],1,0,Code Block??,002ea4d8c7664a6dbb9e8ac970bcf50d,b5b8be87676947c48a5cc2d7c0af965e
1db71931-aac7-4e82-b5b8-5c7bcf16332f,DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],9,8,Zero Touch,b0adfdfb226249ffa7cc5b6daed4aaaf,88de44b1ad8b425dacde34da56e88c83
==@var[]..[]_var[]..[],DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],6,0,Code Block??,f58796d8bfd34de3a934f248ebf22e15,88de44b1ad8b425dacde34da56e88c83
DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],archilab.Revit.Selection.Select.ByElementId@var,81,81,DSCore,88de44b1ad8b425dacde34da56e88c83,c23fd434e93643b99b0f09db150506af
a8b0f382-e8bc-4198-93af-a93c1afcf265,DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],6,2,Zero Touch,b63ea965728a4f6595f5b0ada9630bab,1cb4b763c4cd47fb99d677a3bb8c89b5
b223cace-86e4-435e-8e6c-94a60e29ecb6,1db71931-aac7-4e82-b5b8-5c7bcf16332f,8,0,Zero Touch,53e88a8dd4814f68b606214fd3f0a71b,b0adfdfb226249ffa7cc5b6daed4aaaf
_UI.MultipleInputForm_++,5c6eba64-17ff-4764-9134-0afcdb6716a4,10,10,_UI,662f14de44904c419280b81ff3b7bdcd,5d8306bf06c24aafa37cf35294ea646c
5c6eba64-17ff-4764-9134-0afcdb6716a4,b223cace-86e4-435e-8e6c-94a60e29ecb6,0,0,Zero Touch,5d8306bf06c24aafa37cf35294ea646c,53e88a8dd4814f68b606214fd3f0a71b
_UI.FilePath_Data,_UI.MultipleInputForm_++,0,0,_UI,a362ee84145449b293b4a77c9ad78297,662f14de44904c419280b81ff3b7bdcd
DSCore.IO.Image.ReadFromFile@var,_UI.MultipleInputForm_++,3,0,DSCore,46e0350ca3ce43568735758fe8221272,662f14de44904c419280b81ff3b7bdcd
DSCore.List.Flatten@var[]..[]_int,+@var[]..[]_var[]..[],47,47,DSCore,e63184e30588456d82837b61d808f2b4,c932eccaceab49d88213e72c666f6911
archilab.Revit.Selection.Select.ByElementId@var,a8b0f382-e8bc-4198-93af-a93c1afcf265,0,0,archilab,c23fd434e93643b99b0f09db150506af,b63ea965728a4f6595f5b0ada9630bab
Revit.Elements.CurveElement.Curve,Autodesk.DesignScript.Geometry.Curve.PointsAtEqualSegmentLength@int,2,1,Revit,f92c5894967e42aeb6d8b2bd0f92291b,e85495584e96474980de27a49a4526f3
Autodesk.DesignScript.Geometry.Curve.PointsAtEqualSegmentLength@int,DSCore.List.Flatten@var[]..[]_int,1,1,Autodesk,e85495584e96474980de27a49a4526f3,e9745700625849f9b659bfe6323e2872
92960965-5bfc-41ab-9ceb-d61917dfe6c5,a2d5ef3c-b3a2-403f-8b95-fd94457ce395,1,1,Zero Touch,a5ff29fc5fa844b385ea6bb331462b28,a8a2c54c4b6949688681ba42ed240df7
Autodesk.DesignScript.Geometry.Plane.ByOriginNormal@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Vector,_BoundingBox.PerimeterCurvesOnPlane,0,0,Autodesk,8b0a6b791f4b458a9cab80267ea309e0,b91cf371c410410fa28dfe2a876f96d8
Autodesk.DesignScript.Geometry.BoundingBox.ByGeometry@Autodesk.DesignScript.Geometry.Geometry[],DSCore.List.Flatten@var[]..[]_int,0,0,Autodesk,18ff4673dd9c4b03be12b7cad9300a29,f7d72f9d73ef4682ab1abf498c683311
2c408f1b-9655-4d54-8984-c9062c87b41d,DSCore.String.ToNumber@string,0,0,Zero Touch,ae7fbfaccda740cfbc4468cc1ecd6ffd,1d472d68b25b4487b70607f739e76344
Geometry.Points.NumbersToPoint@double[],DSCore.List.Flatten@var[]..[]_int,0,0,Geometry,736f3805dd2b46f980d6ccce9b03d346,3b0e0e07690041d8ab0adc4977b8bb95
Autodesk.DesignScript.Geometry.Geometry.Translate@double_double_double,Autodesk.DesignScript.Geometry.Geometry.Rotate@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Vector_double,0,0,Autodesk,0ef94e93b6ba46ce956303ce2e8a8c90,a6a91183a6a349c98062d836b24c1c23
Autodesk.DesignScript.Geometry.Geometry.Rotate@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Vector_double,Revit.Elements.FamilyInstance.ByPoint@Revit.Elements.FamilyType_Autodesk.DesignScript.Geometry.Point,0,0,Autodesk,a6a91183a6a349c98062d836b24c1c23,1be337bccc6a4a9dac663df3125d4311
Autodesk.DesignScript.Geometry.Vector.ZAxis,Autodesk.DesignScript.Geometry.Geometry.Rotate@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Vector_double,0,0,Autodesk,d39586c2e7394388b27ce0909c4b2c1f,a6a91183a6a349c98062d836b24c1c23
Autodesk.DesignScript.Geometry.Point.Origin,Autodesk.DesignScript.Geometry.Geometry.Rotate@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Vector_double,0,0,Autodesk,3a5daa72d46342a5842da4e78582f34e,a6a91183a6a349c98062d836b24c1c23
_All_Family_Types_Of_Category,DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],0,0,Zero Touch,81cd924d6127402fb7f2f4122d7be527,47689cf1382d45dda81db8337399992c
DSCore.String.Contains@string_string_bool,DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],17,0,DSCore,189fa72330d64489b1babb7b3cfb9c0f,47689cf1382d45dda81db8337399992c
Revit.Elements.Element.GetParameterValueByName@string,DSCore.List.Flatten@var[]..[]_int,9,8,Revit,87391469ea794ba8a4af6727770114fd,3d1c45796f18464f9d541ba07110ddc9
_Document.ActiveViewFromCurrentDocument,_Schedule.GetCalculatedValues,4,1,_Document,e5c3ca26fc68433abdd6da920edcc0ac,78e44557ce2249d3a997f834bf691bf9
Revit.Elements.Views.ScheduleView.Fields,_UI.DropDown_Data,5,0,Revit,0318f05d464243f993541aa616c3ee46,da4b8b4d35404da9b2da2153350a6409
_Math.Ceiling+,/@var[]..[]_var[]..[],1,0,_Math,b018e7e51ccc497e88a91fd0d7af12ca,8d41b24a2ac54cadac9b8da5f423c216
/@var[]..[]_var[]..[],Revit.Elements.Element.SetParameterByName@string_var,1,0,Code Block??,8d41b24a2ac54cadac9b8da5f423c216,550b8806061646f7b12a9317983613ab
DSCore.String.ToNumber@string,_Math.Ceiling+,1,0,DSCore,c84a737f04904e959cbd2fd3bb9c6764,b018e7e51ccc497e88a91fd0d7af12ca
DSCore.List.FirstIndexOf@var[]..[]_var,DSCore.List.GetItemAtIndex@var[]..[]_int,45,0,DSCore,7e9063de39a3416b86de77f94cd28145,ef19e145a5874320b650894bd2fc8831
DSCore.String.Join@string_string[],DSCore.List.Flatten@var[]..[]_int,0,0,DSCore,fa58147575d14f6b85a232ca3aa6ac4a,95a9ba78b564492180dc60c08713362d
6cf7f3b9-69ab-40da-b41c-62068370e1b8,DSCore.List.GetItemAtIndex@var[]..[]_int,45,22,Zero Touch,faccf85521ba48d98aca3717ba376d7d,2a249509ff9048e48621609d4802c68d
*@var[]..[]_var[]..[],Revit.Elements.Element.SetParameterByName@string_var,7,0,Code Block??,20d03ea8aa2e4e1f850d43734e86716c,8240e8507a164589973ac4e693c88614
DSCore.List.AddItemToFront@var[]..[]_var[]..[],DSOffice.Data.ExportExcel@string_string_int_int_var[][]_bool,1,0,DSCore,71a9115cb8b444d8b51c5115781de96b,7d145ce7bb754c989200a339fc066288
DSCore.List.AddItemToEnd@var[]..[]_var[]..[],DSCore.List.AddItemToFront@var[]..[]_var[]..[],1,0,DSCore,cf1f8b273e454b3a9d14bfa811677098,71a9115cb8b444d8b51c5115781de96b
_Elements_in_Space,DSCore.List.Flatten@var[]..[]_int,1,0,_Elements_in_Space,0bf888dc85a941a9bc5ba55f790877b4,73d7f8fbdd7241b19da4886d1774423c
DSCore.List.OfRepeatedItem@var[]..[]_int,DSCore.List.Flatten@var[]..[]_int,1,0,DSCore,d8b5b6a7df0646cc9d062936c27f1d65,1d28059617d947da9dab466ebb92e832
Revit.Elements.Grid.Curve,Autodesk.DesignScript.Geometry.Curve.StartPoint,0,0,Revit,5612a7b4db2c4f3589be65e9aa60b653,fc17365788454f619c6cfb8ad1d93ed4
Autodesk.DesignScript.Geometry.Curve.StartPoint,DSCore.List.FirstItem@var[]..[],3,3,Autodesk,fc17365788454f619c6cfb8ad1d93ed4,61f2c02f0d4443adabf604dc03a98644
DSCore.List.FirstItem@var[]..[],Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Point,0,0,DSCore,61f2c02f0d4443adabf604dc03a98644,c1926bcdc3604b40a46100314e08a20b
DSCore.List.LastItem@var[]..[],Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Point,0,0,DSCore,7154d63d2cf248b8a6a7c3ecb788dee5,c1926bcdc3604b40a46100314e08a20b
Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Point,Autodesk.DesignScript.Geometry.Curve.Offset@double,0,0,Autodesk,c1926bcdc3604b40a46100314e08a20b,e02957a797304316baf23798f30bb206
Revit.Elements.Element.Curves,Autodesk.DesignScript.Geometry.Curve.StartPoint,1,0,Revit,5d184e933b8f49748603d97062f79a7a,f459192cfbe04b3d82269f5fe9c5164c
_DetailCurve.ByCurve+,Revit.Elements.Element.Curves,0,0,_DetailCurve,fcb7876491eb409697b1a6582b9857f3,3a27c05721e543438b3ebfc211a12d11
Revit.Elements.Element.Geometry,DSCore.List.Flatten@var[]..[]_int,4,2,Revit,df43ff465d204a3b9e6ff4ca86ecf341,7be9826db3bf459bb25365317712144a
_List.FilterByString,DSCore.List.Flatten@var[]..[]_int,2,0,_List,e44ed95d04b640bb8eb7f6b9eedebca3,be2954801f3b49c8b5aa69359a720cfb
036abfeb-d77d-40e7-8be0-78a41034d11d,DSCore.String.Contains@string_string_bool,1,1,Zero Touch,39f6a06493584d3c8c9af56f0c7c1249,dd50173163d4496dab15c43f279d2d32
DSCore.IO.FileSystem.FileName@string_bool,DSCore.String.Replace@string_string_string,0,0,DSCore,a8ceb43ce1f44a8a98c01b577660c577,2661444113b94b03b302b71ab07c63fe
DSCore.String.Replace@string_string_string,DSCore.String.Split@string_string[],0,0,DSCore,3adb4787a0164647aa7a99cdec081b22,2826081fd7884ddf9ca780551395749f
Autodesk.DesignScript.Geometry.PolySurface.Surfaces,Autodesk.DesignScript.Geometry.Surface.NormalAtParameter@double_double,2,2,Autodesk,0c0ca946389d49269427444869993db2,c6725fa1abc14164b0b6693a62ac0e9b
Autodesk.DesignScript.Geometry.PolySurface.ByLoft@Autodesk.DesignScript.Geometry.Curve[],Autodesk.DesignScript.Geometry.PolySurface.Surfaces,0,0,Autodesk,ee63541e59424f22bfee709951d1de0e,0c0ca946389d49269427444869993db2
Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector_double,fd584cb1-8b89-47b9-bf78-d7fb8912ff98,2,1,Autodesk,499380db5265429c9b533f8514f038a2,55366dd1b8754150b0357062b1379dc8
Autodesk.DesignScript.Geometry.Surface.NormalAtParameter@double_double,Autodesk.DesignScript.Geometry.Geometry.Translate@Autodesk.DesignScript.Geometry.Vector_double,1,0,Autodesk,c6725fa1abc14164b0b6693a62ac0e9b,499380db5265429c9b533f8514f038a2
Autodesk.DesignScript.Geometry.Curve.ExtrudeAsSolid@double,Autodesk.DesignScript.Geometry.Solid.Difference@Autodesk.DesignScript.Geometry.Solid,1,1,Autodesk,afbad15afebe4bfe9b8716ca5c5f3bf9,0c1d0571f53b4bb69d77f5095ca3c3dc
Autodesk.DesignScript.Geometry.Solid.ByUnion@Autodesk.DesignScript.Geometry.Solid[],Autodesk.DesignScript.Geometry.Solid.Difference@Autodesk.DesignScript.Geometry.Solid,0,0,Autodesk,1420cd092ca84444a039dcbe894adebd,0c1d0571f53b4bb69d77f5095ca3c3dc
_Element.IsOfType,DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],1,0,_Element,c2c4c7a9aea34ba484031311f855c083,30ceea0049b64662b87deb403a2ab5d1
DSCore.List.GroupByKey@var[]..[]_var[]..[],DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],1,1,DSCore,cad55675a3e3444391026a2445324380,3e8621b096b2433b97a3f5b022b7a5bc
DSCore.List.Sort@var[],_List.FilterByString,0,0,DSCore,0c3e6c6d68ac465dbdf1ae1188d0ea52,29e90e71b9f54963a8ba9ba8a4fd7d60
DSCore.Color.ByARGB@int_int_int_int,Modifiers.GeometryColor.ByGeometryColor@Autodesk.DesignScript.Geometry.Geometry_DSCore.Color,0,0,DSCore,9f3b7bf635594afb860f522b50deeac7,6e625dbf84bf43538ce3f7dbd35f4d35
DSOffice.Data.ImportCSV@string_bool,DSCore.List.GetItemAtIndex@var[]..[]_int,1,0,DSOffice,9cb20c5ba65740aaadc57f7146a7dab4,622b1f22ac264175a89186d8ed58dbf4
Lists.DataSets.CreateDataTable@string_string[]_var[][],MachineLearning.Classification.NaiveBayesClassifier@string[]_var_string[]_string_int,1,0,Lists,1a0b4b8c439b4537ae584eb3ca28fb45,956fa5e74fdb4b709f705b5dda582ab3
d46bc80c-81c9-49db-909f-d091d3f2617f,Revit.Elements.Element.GetParameterValueByName@string,0,0,Zero Touch,1e4f0ead4731414dae8a64fb1b19e9fa,892247028e6c4825a9f32af37128c006
Revit.Elements.FamilyType.Name,DSCore.String.StartsWith@string_string_bool,0,0,Revit,f7d077abd32043408919745152ccae5e,eb92afb0ebe449bdba9a85db9376f18e
DSCore.String.StartsWith@string_string_bool,DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],0,0,DSCore,eb92afb0ebe449bdba9a85db9376f18e,11eee97dbfc24637860f76a83a0824f0
Autodesk.DesignScript.Geometry.Geometry.BoundingBox,Autodesk.DesignScript.Geometry.BoundingBox.Contains@Autodesk.DesignScript.Geometry.Point,0,0,Autodesk,c7d4afc9e8de438a9ef28d69838f7356,3d266a6037f24fe3b9a7ecda77890f3b
_Element.IsOfCategory,DSCore.List.FilterByBoolMask@var[]..[]_var[]..[],0,0,_Element,be9f6f4130334e26b55513e4a6d4d1ea,30ceea0049b64662b87deb403a2ab5d1
Autodesk.DesignScript.Geometry.Point.ByCoordinates@double_double_double,Autodesk.DesignScript.Geometry.Line.ByStartPointEndPoint@Autodesk.DesignScript.Geometry.Point_Autodesk.DesignScript.Geometry.Point,1,0,Autodesk,8ec740b7e8ea49b69c57ee9586be8e08,c8f30194a3ba49f29ad8e4ec1ebf000f
